title: PositionPal - Project Management
description: Project Management Report for the PositionPal project
url: "https://position-pal.github.io"
baseurl: "/PM-report"

# Rendering
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  math_engine: mathjax
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

# Theme and plugins
remote_theme: sighingnow/jekyll-gitbook
gitbook_version: 3.2.3
toc:
  enabled: true
  h_min: 1
  h_max: 3
collections:
  report:
    output: true
    sort_by: date
    permalink: /:collection/:path/
  attachments:
    output: true
    sort_by: date
    permalink: /:collection/:path/
page_width: 1000px
syntax_highlighter_style: colorful
extra_css:
  - extras/extra-css.css
permalink: /:categories/:year-:month-:day-:title:output_ext
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-readme-index
  - jemoji